### ISSUE TITLE
Apps configured for Cypress 10.10.0

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/component-testing-quickstart-apps#2]
The example apps:

- angular
- react
- svelte
- vue

are configured with `cypress@10.10.0` before Component Testing because GA with [cypress@11.0.0](https://docs.cypress.io/guides/references/changelog#11-0-0) for React, Next.js, Angular, and Vue.

The examples should be updated to the latest version of Cypress (currently 12.x).

**Comment by jordanpowell88** [comment]
Closed in https://github.com/cypress-io/component-testing-quickstart-apps/pull/7
