### ISSUE TITLE
Archive repo component-testing-quickstart-apps

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/component-testing-quickstart-apps#3]
- PR https://github.com/cypress-io/cypress-documentation/pull/5389 removes references to https://github.com/cypress-io/component-testing-quickstart-apps

- If this repo is no longer needed then it should be archived. It is in any case not up-to-date with latest versions. See
    - #1 
    - #2

**Comment by jordanpowell88** [comment]
We want to keep these getting started apps per https://github.com/cypress-io/cypress-documentation/pull/5404

**Comment by MikeMcC399** [comment]
@jordanpowell88 

Thanks! I wasn't sure about the plans.

I will close this issue in that case.

**Comment by jordanpowell88** [comment]
Thank you! I am working on updating the repo now
